[package]
name = "jsondiff"
version = "0.1.0"
authors = ["Jesús Espino <jespinog@gmail.com>"]

[dependencies]
serde = "*"
serde_json = "*"
clap = "*"
log = "*"
loggerv = "*"

[lib]
name = "jsondiff"
path = "src/lib/mod.rs"

[[bin]]
name = "json-diff"
path = "src/bin.rs"
